I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 443, in script
    Reno "Ummm, Hey, I know this is random, but I have a question."
Exception: Sayer 'Reno' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 443, in script
    Reno "Ummm, Hey, I know this is random, but I have a question."
  File "C:\Users\RIT0002\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\RIT0002\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Reno' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Danganronpa Sorrows End 1.0 - Alpha
Thu Aug 13 16:35:17 2020
